<a href="https://colab.research.google.com/github/n0vemberain/Machine_Learning_A_to_Z/blob/main/Data_PreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing Data Set

In [3]:
dataset = pd.read_csv('Data-2.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(X)

[['France' 25.0 50000.0]
 ['France' 30.0 60000.0]
 ['India' nan 52000.0]
 ['India' 35.0 nan]
 ['Germany' 40.0 70000.0]
 ['UK' 22.0 nan]
 ['USA' nan 48000.0]
 ['India' 29.0 55000.0]
 ['UK' 31.0 62000.0]
 ['UK' 28.0 58000.0]
 ['France' 45.0 nan]
 ['UK' nan 75000.0]
 ['France' 38.0 72000.0]
 ['Germany' 26.0 63000.0]
 ['UK' 27.0 54000.0]
 ['France' nan nan]
 ['Germany' 33.0 66000.0]
 ['USA' 34.0 68000.0]
 ['Germany' 36.0 56000.0]
 ['France' 32.0 59000.0]]


In [5]:
print(y)

['Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No']


# Taking Care of missing data

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy= 'mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [7]:
print(X)

[['France' 25.0 50000.0]
 ['France' 30.0 60000.0]
 ['India' 31.9375 52000.0]
 ['India' 35.0 60500.0]
 ['Germany' 40.0 70000.0]
 ['UK' 22.0 60500.0]
 ['USA' 31.9375 48000.0]
 ['India' 29.0 55000.0]
 ['UK' 31.0 62000.0]
 ['UK' 28.0 58000.0]
 ['France' 45.0 60500.0]
 ['UK' 31.9375 75000.0]
 ['France' 38.0 72000.0]
 ['Germany' 26.0 63000.0]
 ['UK' 27.0 54000.0]
 ['France' 31.9375 60500.0]
 ['Germany' 33.0 66000.0]
 ['USA' 34.0 68000.0]
 ['Germany' 36.0 56000.0]
 ['France' 32.0 59000.0]]


# Encoding Categorical Data Independent Data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X =np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 0.0 0.0 25.0 50000.0]
 [1.0 0.0 0.0 0.0 0.0 30.0 60000.0]
 [0.0 0.0 1.0 0.0 0.0 31.9375 52000.0]
 [0.0 0.0 1.0 0.0 0.0 35.0 60500.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 70000.0]
 [0.0 0.0 0.0 1.0 0.0 22.0 60500.0]
 [0.0 0.0 0.0 0.0 1.0 31.9375 48000.0]
 [0.0 0.0 1.0 0.0 0.0 29.0 55000.0]
 [0.0 0.0 0.0 1.0 0.0 31.0 62000.0]
 [0.0 0.0 0.0 1.0 0.0 28.0 58000.0]
 [1.0 0.0 0.0 0.0 0.0 45.0 60500.0]
 [0.0 0.0 0.0 1.0 0.0 31.9375 75000.0]
 [1.0 0.0 0.0 0.0 0.0 38.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 26.0 63000.0]
 [0.0 0.0 0.0 1.0 0.0 27.0 54000.0]
 [1.0 0.0 0.0 0.0 0.0 31.9375 60500.0]
 [0.0 1.0 0.0 0.0 0.0 33.0 66000.0]
 [0.0 0.0 0.0 0.0 1.0 34.0 68000.0]
 [0.0 1.0 0.0 0.0 0.0 36.0 56000.0]
 [1.0 0.0 0.0 0.0 0.0 32.0 59000.0]]


# Encoding Dependent Data

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[1 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 0 1 1 0]


# Splitting Data Set

In [17]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 1)

In [18]:
print(X_train)

[[0.0 0.0 1.0 0.0 0.0 31.9375 52000.0]
 [0.0 0.0 0.0 1.0 0.0 27.0 54000.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 70000.0]
 [0.0 0.0 0.0 0.0 1.0 34.0 68000.0]
 [0.0 0.0 1.0 0.0 0.0 29.0 55000.0]
 [1.0 0.0 0.0 0.0 0.0 30.0 60000.0]
 [0.0 1.0 0.0 0.0 0.0 26.0 63000.0]
 [1.0 0.0 0.0 0.0 0.0 25.0 50000.0]
 [1.0 0.0 0.0 0.0 0.0 32.0 59000.0]
 [0.0 1.0 0.0 0.0 0.0 36.0 56000.0]
 [0.0 0.0 0.0 1.0 0.0 28.0 58000.0]
 [1.0 0.0 0.0 0.0 0.0 31.9375 60500.0]
 [0.0 0.0 0.0 1.0 0.0 31.0 62000.0]
 [1.0 0.0 0.0 0.0 0.0 38.0 72000.0]
 [0.0 0.0 0.0 1.0 0.0 31.9375 75000.0]
 [0.0 0.0 0.0 1.0 0.0 22.0 60500.0]]


In [19]:
print(X_test)

[[0.0 0.0 1.0 0.0 0.0 35.0 60500.0]
 [0.0 1.0 0.0 0.0 0.0 33.0 66000.0]
 [0.0 0.0 0.0 0.0 1.0 31.9375 48000.0]
 [1.0 0.0 0.0 0.0 0.0 45.0 60500.0]]


In [20]:
print(y_train)

[1 0 0 1 1 0 1 1 0 1 1 1 1 1 0 1]


In [21]:
print(y_test)

[1 0 0 1]


# Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,5:] = sc.fit_transform(X_train[:,5:])
X_test[:,5:] = sc.fit_transform(X_test[:,5:])

In [25]:
print(X_train)

[[0.0 0.0 1.0 0.0 0.0 0.2332580808646812 -1.2813393735168088]
 [0.0 0.0 0.0 1.0 0.0 -0.838880879909708 -0.994606087135425]
 [0.0 1.0 0.0 0.0 0.0 1.9839660041545066 1.2992602039156453]
 [0.0 0.0 0.0 0.0 1.0 0.6811135961248691 1.0125269175342615]
 [0.0 0.0 1.0 0.0 0.0 -0.40459674389982886 -0.8512394439447332]
 [1.0 0.0 0.0 0.0 0.0 -0.18745467589488926 -0.13440622799127366]
 [0.0 1.0 0.0 0.0 0.0 -1.0560229479146477 0.29569370158080205]
 [1.0 0.0 0.0 0.0 0.0 -1.273165015919587 -1.5680726598981927]
 [1.0 0.0 0.0 0.0 0.0 0.2468294601149899 -0.27777287118196553]
 [0.0 1.0 0.0 0.0 0.0 1.1153977321347484 -0.7078728007540412]
 [0.0 0.0 0.0 1.0 0.0 -0.6217388119047684 -0.42113951437265745]
 [1.0 0.0 0.0 0.0 0.0 0.2332580808646812 -0.0627229063959277]
 [0.0 0.0 0.0 1.0 0.0 0.029687392110050333 0.15232705839011013]
 [1.0 0.0 0.0 0.0 0.0 1.5496818681446274 1.585993490297029]
 [0.0 0.0 0.0 1.0 0.0 0.2332580808646812 2.016093419869105]
 [0.0 0.0 0.0 1.0 0.0 -1.924591219934406 -0.0627229063959277]]


In [26]:
print(X_test)

[[0.0 0.0 1.0 0.0 0.0 -0.2383467698115848 0.26514390667749954]
 [0.0 1.0 0.0 0.0 0.0 -0.6245288778607349 1.0984533276639268]
 [0.0 0.0 0.0 0.0 1.0 -0.8296881227618459 -1.6287411410189259]
 [1.0 0.0 0.0 0.0 0.0 1.6925637704341656 0.26514390667749954]]
